#!/usr/bin/env python3
"""Rebuild journal/artem/index.md from the entry files.

Usage: python3 journal/artem/tools/build_index.py

Reads the front matter of every entries/*.md file (except _template.md),
validates the fields, and writes index.md with a summary and one row per
entry. Exits non-zero if any entry is invalid.
"""
import re
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENTRIES = ROOT / "entries"
INDEX = ROOT / "index.md"

ALLOWED = {
    "direction": {"long", "short"},
    "category": {"trend", "false_signal", "control"},
    "open_type": {"clean_drive", "delayed_start", "n/a"},
    "source": {"artem", "raschke-x", "both", "analysis"},
    "raschke_listed": {"yes", "no"},
    "values": {"chart-read", "data"},
    "trend_end_capped": {"yes", "no"},
}
REQUIRED = ["date", "ticker", "direction", "category", "open_type", "source"]
TIME = re.compile(r"^\d{2}:\d{2}$")
DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def parse(path):
    text = path.read_text()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        raise ValueError("missing front matter")
    fields = {}
    for line in m.group(1).splitlines():
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields


def validate(f):
    errors = [f"missing {k}" for k in REQUIRED if not f.get(k)]
    for key, allowed in ALLOWED.items():
        if f.get(key) and f[key] not in allowed:
            errors.append(f"{key}={f[key]!r} not in {sorted(allowed)}")
    if f.get("date") and not DATE.match(f["date"]):
        errors.append(f"bad date {f['date']!r}")
    for key in ("extreme_time", "trend_start_time", "trend_end_time"):
        if f.get(key) and not TIME.match(f[key]):
            errors.append(f"bad {key} {f[key]!r} (want HH:MM)")
    chart = f.get("chart")
    if chart and not (ROOT / chart).exists():
        errors.append(f"chart not found: {chart}")
    return errors


def minutes(t):
    h, m = t.split(":")
    return int(h) * 60 + int(m)


def hhmm(n):
    return f"{int(n) // 60:02d}:{int(n) % 60:02d}"


def main():
    rows, failed = [], False
    for path in sorted(ENTRIES.glob("*.md")):
        if path.name.startswith("_"):
            continue
        try:
            f = parse(path)
        except ValueError as e:
            print(f"{path.name}: {e}", file=sys.stderr)
            failed = True
            continue
        errors = validate(f)
        for e in errors:
            print(f"{path.name}: {e}", file=sys.stderr)
        failed |= bool(errors)
        f["_file"] = path.name
        rows.append(f)
    if failed:
        sys.exit(1)

    trends = [r for r in rows if r["category"] == "trend"]
    lines = ["# Artem journal index", "", "Generated by `tools/build_index.py`. Do not edit by hand.", ""]
    lines += ["## Summary", ""]
    lines.append(
        f"- Entries: {len(rows)} (trend {len(trends)}, "
        f"false signal {sum(r['category'] == 'false_signal' for r in rows)}, "
        f"control {sum(r['category'] == 'control' for r in rows)})"
    )
    if trends:
        clean = sum(r["open_type"] == "clean_drive" for r in trends)
        lines.append(f"- Trend opening type: clean drive {clean}, delayed start {len(trends) - clean}")
        lines.append(
            f"- Trend direction: long {sum(r['direction'] == 'long' for r in trends)}, "
            f"short {sum(r['direction'] == 'short' for r in trends)}"
        )
        starts = [minutes(r["trend_start_time"]) for r in trends if r.get("trend_start_time")]
        if starts:
            lines.append(f"- Median trend start: {hhmm(statistics.median(starts))} ET (n={len(starts)})")
        # A capped end is where the chart stopped, not where the trend stopped, so leave it out.
        ends = [minutes(r["trend_end_time"]) for r in trends
                if r.get("trend_end_time") and r.get("trend_end_capped") != "yes"]
        capped = sum(r.get("trend_end_capped") == "yes" for r in trends)
        if ends:
            lines.append(f"- Median time the move ran out: {hhmm(statistics.median(ends))} ET "
                         f"(n={len(ends)}; {capped} excluded because the chart ends mid-trend)")
            lines.append(f"- Moves that ran past 13:00: {sum(t >= 13 * 60 for t in ends)} of {len(ends)}")
    lines += ["", "## Entries", "", "`+` after a time means the chart ends there with the trend still running.", ""]
    lines.append("| Date | Ticker | Dir | Category | Open type | Extreme | Start | Ran out | Raschke | Chart |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for r in sorted(rows, key=lambda r: (r["date"], r["ticker"])):
        extreme = f"{r.get('extreme_price', '')} @ {r.get('extreme_time', '')}".strip(" @")
        ran_out = r.get("trend_end_time", "") + ("+" if r.get("trend_end_capped") == "yes" else "")
        chart = f"[png]({r['chart']})" if r.get("chart") else ""
        lines.append(
            f"| {r['date']} | [{r['ticker']}](entries/{r['_file']}) | {r['direction']} | {r['category']} | "
            f"{r['open_type']} | {extreme} | {r.get('trend_start_time', '')} | {ran_out} | "
            f"{r.get('raschke_listed', '')} | {chart} |"
        )
    INDEX.write_text("\n".join(lines) + "\n")
    print(f"wrote {INDEX.relative_to(ROOT.parent.parent)} ({len(rows)} entries)")


if __name__ == "__main__":
    main()
